### PR TITLE
refactor: i18n

### PR DESCRIPTION
**Pull request by s-yh-china**
I tried to refactor i18n, but it wasn't perfect. To some extent, downstream mod behavior using prettyName would be disrupted (like tweakermore). This still needs to be modified, but it can run.

### CODE REVIEW

**Comment by sakura-ryoko** [comment]
Redirecting to a feature branch for the moment.

**Comment by sakura-ryoko** [comment]
I've added additional options for configs to use the "prettyName" variable from ConfigBase.

If this looks good for you, I will merge it into the Feature Branch so you can continue working on other mods for Chinese.

**Comment by sakura-ryoko** [comment]
All Other translations that I've added was via using Google Translate, basically ... So the quality is not guaranteed .
I may yet add Spanish ?

**Comment by s-yh-china** [comment]
Perhaps waiting for the community would be better
~~Sorry for not being able to reply in a timely manner due to different time zones~~

**Pull request merged**
